name: BlockElevators
version: 1.0
author: kenYUNOT
main: com.kftang.BlockElevators.BlockElevators
website: kftang.com
commands:
  elevator:
    description: Exclude elevator blocks
    usage: /elevator
